config/routes.rb
Rails.application.routes.draw do
  get 'one', to: 'pages#one'
  get 'two', to: 'pages#two'
  get 'three', to: 'pages#three'
  root 'pages#one'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/concerns/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/one.html.erb
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="Elian Rojas Rojas" />
        <title>Viajes a Chile</title>
  
        # <!-- Bootstrap CSS 4.6.0. -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        
        # <!--Google Fonts-->
        <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
        
        # <!-- Fabicon iconos V5.8.1   -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    # <!-- My CSS -->
        <link rel="stylesheet" href="assets/css/style.css">

        <h1>Elian Rojas Rojas</h1
        <body>
        
  <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-inverse ">
  <a class="navbar-brand" href="#"> FIRST APP </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
        <%= link_to('Personal Page', one_path, class: 'nav-link') %>
        <%= link_to('Routes', two_path, class: 'nav-link') %>
        <%= link_to('Project', three_path, class: 'nav-link') %>
      
      </div>
  </div>
  </nav>

<!--JS 3.5.1. -->
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin=" anonymous "></script>

<!-- jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js " integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns " crossorigin="anonymous "></script>

    
<script src="assets/js/script.js"></script>
    
</body>
</html>

app/views/pages/three.html.erb
<h3>Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum AUNQUE NO ME GUSTA USAR LOREM</h3>


<%= link_to('Volver', one_path) %>

app/views/pages/two.html.erb
<h1>Image Rake routs</h1>
<%= link_to('Volver', one_path) %>
<br>
<br>
<%= image_tag 'pantallazo.png' %>